export default function Home() {
  return (
    <div style={{ padding: 40 }}>
      <h1>Real Estate Image Editor</h1>
      <p>Generated by Cursor AI — The full editor will be built on top of this.</p>
    </div>
  );
}
